apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: basic-pool
  namespace: metallb-system
spec:
  autoAssign: true
  addresses:
    - 192.168.0.220-192.168.0.225

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: basic-ads
  namespace: metallb-system
spec:
  ipAddressPools:
    - basic-pool
